export const EMPLOYEES_DETAILS = [
	{
		id: 1,
		name: 'Chaim Bailey',
		email: 'arcu.vestibulum.ante@icloud.ca',
		position: 'Graphics Designer',
		image: '/img/1.jpeg',
		status: 'onboarded',
		address: '24, Grand Lane, New York City, USA, America, Earth, Solar System, Milky Way Galaxy, Universe',
		phone: '+23410989378',
		gender: 'Male',
	},
	{
		id: 2,
		name: 'Pascale Graham',
		email: 'mus.aenean.eget@hotmail.couk',
		position: 'Web Developer',
		status: 'waitlisted',
		address: '24, Grand Lane, New York City, USA',
		phone: '+23410989378',
		gender: 'Male',
	},
	{
		id: 3,
		name: 'Arsenio Wooten',
		email: 'risus.donec@google.ca',
		position: 'Media Manager',
		status: 'waitlisted',
		address: '24, Grand Lane, New York City, USA',
		phone: '+23410989378',
		gender: 'Male',
	},
	{
		id: 4,
		name: 'Michael Santos',
		email: 'porttitor@aol.net',
		position: 'Medical Assistant',
		image: '/img/4.jpeg',
		status: 'onboarded',
		address: '24, Grand Lane, New York City, USA',
		phone: '+23410989378',
		gender: 'Male',
	},
	{
		id: 5,
		name: 'Driscoll Cortez',
		email: 'morbi@icloud.com',
		position: 'Lawyer',
		image: '/img/5.jpeg',
		status: 'onboarded',
		address: '24, Grand Lane, New York City, USA',
		phone: '+23410989378',
		gender: 'Male',
	},
	{
		id: 6,
		name: 'Samantha Alvarado',
		email: 'lectus.pede@protonmail.ca',
		position: 'Laboratory Assistant',
		status: 'waitlisted',
		address: '24, Grand Lane, New York City, USA',
		phone: '+23410989378',
		gender: 'Male',
	},
	{
		id: 7,
		name: 'Solomon Cardenas',
		email: 'commodo@protonmail.edu',
		position: 'Social Worker',
		status: 'waitlisted',
		address: '24, Grand Lane, New York City, USA',
		phone: '+23410989378',
		gender: 'Male',
	},
	{
		id: 8,
		name: 'Cyrus Jackson',
		email: 'posuere.cubilia@icloud.org',
		position: 'Store Manager',
		status: 'waitlisted',
		address: '24, Grand Lane, New York City, USA',
		phone: '+23410989378',
		gender: 'Male',
	},
	{
		id: 9,
		name: 'Lila Hess',
		email: 'cum.sociis.natoque@google.net',
		position: 'Stockbroker',
		status: 'waitlisted',
		address: '24, Grand Lane, New York City, USA',
		phone: '+23410989378',
		gender: 'Male',
	},
	{
		id: 10,
		name: 'Josephine Tucker',
		email: 'posuere.cubilia@protonmail.ca',
		position: 'Judge',
		status: 'waitlisted',
		address: '24, Grand Lane, New York City, USA',
		phone: '+23410989378',
		gender: 'Male',
	},
	{
		id: 11,
		name: 'Tallulah Suarez',
		email: 'pede.et@icloud.edu',
		position: 'Devops Engineer',
		image: '/img/11.jpeg',
		status: 'onboarded',
		address: '24, Grand Lane, New York City, USA',
		phone: '+23410989378',
		gender: 'Male',
	},
	{
		id: 12,
		name: 'Orlando Knowles',
		email: 'aliquet.lobortis@hotmail.net',
		position: 'Comedy Writer',
		image: '/img/12.jpeg',
		status: 'onboarded',
		address: '24, Grand Lane, New York City, USA',
		phone: '+23410989378',
		gender: 'Male',
	},
	{
		id: 13,
		name: 'Bert Berger',
		email: 'purus@protonmail.ca',
		position: 'MC/Compere',
		image: '/img/13.jpeg',
		status: 'onboarded',
		address: '24, Grand Lane, New York City, USA',
		phone: '+23410989378',
		gender: 'Male',
	},
	{
		id: 14,
		name: 'Kiara Perry',
		email: 'quis@yahoo.ca',
		position: 'Police Officer',
		status: 'waitlisted',
		address: '24, Grand Lane, New York City, USA',
		phone: '+23410989378',
		gender: 'Male',
	},
	{
		id: 15,
		name: 'Rhiannon Henson',
		email: 'sit@outlook.net',
		position: 'Politician',
		image: '/img/15.jpeg',
		status: 'onboarded',
		address: '24, Grand Lane, New York City, USA',
		phone: '+23410989378',
		gender: 'Male',
	},
	{
		id: 16,
		name: 'Damian Vargas',
		email: 'adipiscing.non.luctus@outlook.couk',
		position: 'Medical Doctor',
		status: 'waitlisted',
		address: '24, Grand Lane, New York City, USA',
		phone: '+23410989378',
		gender: 'Male',
	},
	{
		id: 17,
		name: 'Emily Cooper',
		email: 'emily.cooper@example.com',
		position: 'Marketing Specialist',
		image: '/img/7.jpeg',
		status: 'onboarded',
		address: '24, Grand Lane, New York City, USA',
		phone: '+23410989378',
		gender: 'Female',
	},
	{
		id: 18,
		name: 'Oliver Reed',
		email: 'oliver.reed@example.com',
		position: 'Software Engineer',
		status: 'waitlisted',
		address: '24, Grand Lane, New York City, USA',
		phone: '+23410989378',
		gender: 'Male',
	},
	{
		id: 19,
		name: 'Sophia Campbell',
		email: 'sophia.campbell@example.com',
		position: 'Human Resources Manager',
		image: '/img/9.jpeg',
		status: 'onboarded',
		address: '24, Grand Lane, New York City, USA',
		phone: '+23410989378',
		gender: 'Female',
	},
	{
		id: 20,
		name: 'Maxwell Price',
		email: 'maxwell.price@example.com',
		position: 'Financial Analyst',
		status: 'waitlisted',
		address: '24, Grand Lane, New York City, USA',
		phone: '+23410989378',
		gender: 'Male',
	},
	{
		id: 21,
		name: 'Ava Richardson',
		email: 'ava.richardson@example.com',
		position: 'Customer Service Representative',
		image: '/img/11.jpeg',
		status: 'onboarded',
		address: '24, Grand Lane, New York City, USA',
		phone: '+23410989378',
		gender: 'Female',
	},
	{
		id: 22,
		name: 'Henry Morgan',
		email: 'henry.morgan@example.com',
		position: 'Product Manager',
		image: '/img/12.jpeg',
		status: 'onboarded',
		address: '24, Grand Lane, New York City, USA',
		phone: '+23410989378',
		gender: 'Male',
	},
	{
		id: 23,
		name: 'Amelia Brooks',
		email: 'amelia.brooks@example.com',
		position: 'Sales Executive',
		status: 'waitlisted',
		address: '24, Grand Lane, New York City, USA',
		phone: '+23410989378',
		gender: 'Female',
	},
	{
		id: 24,
		name: 'Daniel Turner',
		email: 'daniel.turner@example.com',
		position: 'Data Analyst',
		image: '/img/14.jpeg',
		status: 'onboarded',
		address: '24, Grand Lane, New York City, USA',
		phone: '+23410989378',
		gender: 'Male',
	},
	{
		id: 25,
		name: 'Mia Johnson',
		email: 'mia.johnson@example.com',
		position: 'Project Manager',
		status: 'waitlisted',
		address: '24, Grand Lane, New York City, USA',
		phone: '+23410989378',
		gender: 'Female',
	},
	{
		id: 26,
		name: 'William Hughes',
		email: 'william.hughes@example.com',
		position: 'Business Development Manager',
		image: '/img/16.jpeg',
		status: 'onboarded',
		address: '24, Grand Lane, New York City, USA',
		phone: '+23410989378',
		gender: 'Male',
	},
	{
		id: 27,
		name: 'Charlotte Anderson',
		email: 'charlotte.anderson@example.com',
		position: 'Graphic Designer',
		status: 'waitlisted',
		address: '24, Grand Lane, New York City, USA',
		phone: '+23410989378',
		gender: 'Female',
	},
	{
		id: 28,
		name: 'James Mitchell',
		email: 'james.mitchell@example.com',
		position: 'Software Developer',
		image: '/img/2.jpeg',
		status: 'onboarded',
		address: '24, Grand Lane, New York City, USA',
		phone: '+23410989378',
		gender: 'Male',
	},
	{
		id: 29,
		name: 'Grace Peterson',
		email: 'grace.peterson@example.com',
		position: 'Marketing Manager',
		status: 'waitlisted',
		address: '24, Grand Lane, New York City, USA',
		phone: '+23410989378',
		gender: 'Female',
	},
	{
		id: 30,
		name: 'Benjamin Scott',
		email: 'benjamin.scott@example.com',
		position: 'Data Scientist',
		image: '/img/3.jpeg',
		status: 'onboarded',
		address: '24, Grand Lane, New York City, USA',
		phone: '+23410989378',
		gender: 'Male',
	},
	{
		id: 31,
		name: 'Emma Parker',
		email: 'emma.parker@example.com',
		position: 'Operations Manager',
		image: '/img/4.jpeg',
		status: 'onboarded',
		address: '24, Grand Lane, New York City, USA',
		phone: '+23410989378',
		gender: 'Female',
	},
	{
		id: 32,
		name: 'Alexander Turner',
		email: 'alexander.turner@example.com',
		position: 'IT Specialist',
		status: 'waitlisted',
		address: '24, Grand Lane, New York City, USA',
		phone: '+23410989378',
		gender: 'Male',
	},
	{
		id: 33,
		name: 'Sophie Hill',
		email: 'sophie.hill@example.com',
		position: 'Customer Support Representative',
		image: '/img/5.jpeg',
		status: 'onboarded',
		address: '24, Grand Lane, New York City, USA',
		phone: '+23410989378',
		gender: 'Female',
	},
	{
		id: 34,
		name: 'Jacob Ward',
		email: 'jacob.ward@example.com',
		position: 'Financial Advisor',
		status: 'waitlisted',
		address: '24, Grand Lane, New York City, USA',
		phone: '+23410989378',
		gender: 'Male',
	},
	{
		id: 35,
		name: 'Ella Morris',
		email: 'ella.morris@example.com',
		position: 'Sales Manager',
		image: '/img/6.jpeg',
		status: 'onboarded',
		address: '24, Grand Lane, New York City, USA',
		phone: '+23410989378',
		gender: 'Female',
	},
	{
		id: 36,
		name: 'William Turner',
		email: 'william.turner@example.com',
		position: 'Business Analyst',
		image: '/img/8.jpeg',
		status: 'onboarded',
		address: '24, Grand Lane, New York City, USA',
		phone: '+23410989378',
		gender: 'Male',
	},
	{
		id: 37,
		name: 'Victoria Hughes',
		email: 'victoria.hughes@example.com',
		position: 'Public Relations Manager',
		status: 'waitlisted',
		address: '24, Grand Lane, New York City, USA',
		phone: '+23410989378',
		gender: 'Female',
	},
	{
		id: 38,
		name: 'David Walker',
		email: 'david.walker@example.com',
		position: 'Technical Writer',
		image: '/img/10.jpeg',
		status: 'onboarded',
		address: '24, Grand Lane, New York City, USA',
		phone: '+23410989378',
		gender: 'Male',
	},
	{
		id: 39,
		name: 'Sophia Turner',
		email: 'sophia.turner@example.com',
		position: 'HR Specialist',
		status: 'waitlisted',
		address: '24, Grand Lane, New York City, USA',
		phone: '+23410989378',
		gender: 'Female',
	},
	{
		id: 40,
		name: 'John Carter',
		email: 'john.carter@example.com',
		position: 'Project Coordinator',
		image: '/img/13.jpeg',
		status: 'onboarded',
		address: '24, Grand Lane, New York City, USA',
		phone: '+23410989378',
		gender: 'Male',
	},
];
