export const EMPLOYEES_DETAILS = [
	{
		id: 1,
		name: 'Chaim Bailey',
		email: 'arcu.vestibulum.ante@icloud.ca',
		position: 'Graphics Designer',
		image: '/img/1.jpeg',
		status: 'onboarded',
	},
	{
		id: 2,
		name: 'Pascale Graham',
		email: 'mus.aenean.eget@hotmail.couk',
		position: 'Web Developer',
		image: '/img/2.jpeg',
		status: 'waitlisted',
	},
	{
		id: 3,
		name: 'Arsenio Wooten',
		email: 'risus.donec@google.ca',
		position: 'Media Manager',
		image: '/img/3.jpeg',
		status: 'waitlisted',
	},
	{
		id: 4,
		name: 'Michael Santos',
		email: 'porttitor@aol.net',
		position: 'Medical Assistant',
		image: '/img/4.jpeg',
		status: 'onboarded',
	},
	{
		id: 5,
		name: 'Driscoll Cortez',
		email: 'morbi@icloud.com',
		position: 'Lawyer',
		image: '/img/5.jpeg',
		status: 'onboarded',
	},
	{
		id: 6,
		name: 'Samantha Alvarado',
		email: 'lectus.pede@protonmail.ca',
		position: 'Laboratory Assistant',
		image: '/img/6.jpeg',
		status: 'waitlisted',
	},
	{
		id: 7,
		name: 'Solomon Cardenas',
		email: 'commodo@protonmail.edu',
		position: 'Social Worker',
		image: '/img/7.jpeg',
		status: 'waitlisted',
	},
	{
		id: 8,
		name: 'Cyrus Jackson',
		email: 'posuere.cubilia@icloud.org',
		position: 'Store Manager',
		image: '/img/8.jpeg',
		status: 'waitlisted',
	},
	{
		id: 9,
		name: 'Lila Hess',
		email: 'cum.sociis.natoque@google.net',
		position: 'Stockbroker',
		image: '/img/9.jpeg',
		status: 'waitlisted',
	},
	{
		id: 10,
		name: 'Josephine Tucker',
		email: 'posuere.cubilia@protonmail.ca',
		position: 'Judge',
		image: '/img/10.jpeg',
		status: 'waitlisted',
	},
	{
		id: 11,
		name: 'Tallulah Suarez',
		email: 'pede.et@icloud.edu',
		position: 'Devops Engineer',
		image: '/img/11.jpeg',
		status: 'onboarded',
	},
	{
		id: 12,
		name: 'Orlando Knowles',
		email: 'aliquet.lobortis@hotmail.net',
		position: 'Comedy Writer',
		image: '/img/12.jpeg',
		status: 'onboarded',
	},
	{
		id: 13,
		name: 'Bert Berger',
		email: 'purus@protonmail.ca',
		position: 'MC/Compere',
		image: '/img/13.jpeg',
		status: 'onboarded',
	},
	{
		id: 14,
		name: 'Kiara Perry',
		email: 'quis@yahoo.ca',
		position: 'Police Officer',
		image: '/img/14.jpeg',
		status: 'waitlisted',
	},
	{
		id: 15,
		name: 'Rhiannon Henson',
		email: 'sit@outlook.net',
		position: 'Politician',
		image: '/img/15.jpeg',
		status: 'onboarded',
	},
	{
		id: 16,
		name: 'Damian Vargas',
		email: 'adipiscing.non.luctus@outlook.couk',
		position: 'Medical Doctor',
		image: '/img/16.jpeg',
		status: 'waitlisted',
	},
];
